/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  ComplexModalContents,
} from './components/m-complex-modal/m-complex-modal';

export namespace Components {
  interface MButton {}
  interface MComplexModal {
    'contents': ComplexModalContents;
    'open': boolean;
  }
  interface MModal {
    'open': boolean;
  }
  interface MPanel {
    'open': boolean;
  }
}

declare global {


  interface HTMLMButtonElement extends Components.MButton, HTMLStencilElement {}
  var HTMLMButtonElement: {
    prototype: HTMLMButtonElement;
    new (): HTMLMButtonElement;
  };

  interface HTMLMComplexModalElement extends Components.MComplexModal, HTMLStencilElement {}
  var HTMLMComplexModalElement: {
    prototype: HTMLMComplexModalElement;
    new (): HTMLMComplexModalElement;
  };

  interface HTMLMModalElement extends Components.MModal, HTMLStencilElement {}
  var HTMLMModalElement: {
    prototype: HTMLMModalElement;
    new (): HTMLMModalElement;
  };

  interface HTMLMPanelElement extends Components.MPanel, HTMLStencilElement {}
  var HTMLMPanelElement: {
    prototype: HTMLMPanelElement;
    new (): HTMLMPanelElement;
  };
  interface HTMLElementTagNameMap {
    'm-button': HTMLMButtonElement;
    'm-complex-modal': HTMLMComplexModalElement;
    'm-modal': HTMLMModalElement;
    'm-panel': HTMLMPanelElement;
  }
}

declare namespace LocalJSX {
  interface MButton extends JSXBase.HTMLAttributes<HTMLMButtonElement> {}
  interface MComplexModal extends JSXBase.HTMLAttributes<HTMLMComplexModalElement> {
    'contents'?: ComplexModalContents;
    'onDismiss'?: (event: CustomEvent<any>) => void;
    'open'?: boolean;
  }
  interface MModal extends JSXBase.HTMLAttributes<HTMLMModalElement> {
    'onDismiss'?: (event: CustomEvent<any>) => void;
    'open'?: boolean;
  }
  interface MPanel extends JSXBase.HTMLAttributes<HTMLMPanelElement> {
    'onDismiss'?: (event: CustomEvent<any>) => void;
    'open'?: boolean;
  }

  interface IntrinsicElements {
    'm-button': MButton;
    'm-complex-modal': MComplexModal;
    'm-modal': MModal;
    'm-panel': MPanel;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


